export const mockUser = {
  id: 1,
  fullName: 'John Doe',
  email: 'john.doe@bugboard26.dev',
  role: 'Developer',
  avatarUrl: '',
}

export const mockProjects = [
  {
    id: 1,
    name: 'BugBoard26 Core',
    description: 'Main application development and bug tracking',
    totalIssues: 45,
    openIssues: 12,
    closedIssues: 33,
    memberCount: 8,
    updatedAt: '2026-03-30T09:15:00',
  },
  {
    id: 2,
    name: 'Mobile App',
    description: 'iOS and Android mobile applications',
    totalIssues: 28,
    openIssues: 15,
    closedIssues: 13,
    memberCount: 5,
    updatedAt: '2026-03-30T06:30:00',
  },
  {
    id: 3,
    name: 'API Development',
    description: 'RESTful API and backend services',
    totalIssues: 34,
    openIssues: 8,
    closedIssues: 26,
    memberCount: 6,
    updatedAt: '2026-03-29T13:00:00',
  },
  {
    id: 4,
    name: 'Documentation',
    description: 'User guides and technical documentation',
    totalIssues: 12,
    openIssues: 4,
    closedIssues: 8,
    memberCount: 3,
    updatedAt: '2026-03-27T15:00:00',
  },
  {
    id: 5,
    name: 'Infrastructure',
    description: 'DevOps, CI/CD, and cloud infrastructure',
    totalIssues: 19,
    openIssues: 6,
    closedIssues: 13,
    memberCount: 4,
    updatedAt: '2026-03-29T23:45:00',
  },
  {
    id: 6,
    name: 'UI/UX Design',
    description: 'Design system and user interface improvements',
    totalIssues: 23,
    openIssues: 10,
    closedIssues: 13,
    memberCount: 4,
    updatedAt: '2026-03-30T03:10:00',
  },
]

export const mockNotifications = [
  {
    id: 1,
    message: 'Issue BUG-26-41 has been assigned to you',
    issueId: 41,
    read: false,
    createdAt: '2026-03-30T08:50:00',
  },
  {
    id: 2,
    message: 'Project Mobile App was updated',
    issueId: 0,
    read: true,
    createdAt: '2026-03-29T19:20:00',
  },
  {
    id: 3,
    message: 'Issue BUG-26-39 status changed to IN_PROGRESS',
    issueId: 39,
    read: false,
    createdAt: '2026-03-30T07:10:00',
  },
]
